### ISSUE TITLE
PulseAveraging: When enabling OVS, first sweep is shown twice

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#709]
When PA is enabled and then OVS is enabled the first sweep is shown twice in the PA plot.

**Comment by t-b** [comment]
@MichaelHuth Please close if this is already fixed in main.

**Comment by MichaelHuth** [comment]
@t-b I rebased and still see that with the PA_Tests experiment:

![image](https://user-images.githubusercontent.com/29093275/98253984-02e68680-1f7c-11eb-9e03-86d02dd44983.png)

**Comment by t-b** [comment]
@MichaelHuth Thanks. I'll have a look.
